/* ============================================================
   build-text.js — generate the full scripture text data files
   (dev only, not shipped to the browser).

   Input:  ../text-src/*.json — the official Gospel Library text
           (bcbooks/scriptures-json, 2013 edition) + od1.json /
           od2.json scraped from churchofjesuschrist.org.
           This folder is gitignored; text is © Intellectual
           Reserve, Inc. and stays local.
   Output: ../data/text-manifest.js  (volume → chunk file list)
           ../data/text-<vol>-<n>.js (whole books per chunk,
           lazy-loaded by the app one volume at a time)

   Run:    node tools/build-text.js
   ============================================================ */
const fs = require("fs");
const path = require("path");
const SRC = path.join(__dirname, "..", "text-src");
const OUT = path.join(__dirname, "..", "data");
const CHUNK_BYTES = 700 * 1024; // target max per chunk file

/* dataset slug → app book id (only the ones that differ) */
const SLUG_MAP = { "1-jn": "1-john", "2-jn": "2-john", "3-jn": "3-john" };

function fail(msg) { console.error("BUILD FAIL:", msg); process.exit(1); }
function loadVol(f) {
  const p = path.join(SRC, f);
  if (!fs.existsSync(p)) fail("missing input " + f);
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

/* books: [{ id, chapters: { n: [verse,...] } }] */
function volumeBooks(file, key) {
  const j = loadVol(file);
  const arr = key && j[key] ? j[key] : j.books;
  return arr.map(b => {
    const id = SLUG_MAP[b.lds_slug] || b.lds_slug;
    const chapters = {};
    const list = b.chapters || [];
    list.forEach((c, i) => {
      const n = c.chapter || i + 1;
      if (chapters[n]) fail(file + " duplicate chapter " + id + " " + n);
      const verses = c.verses.map(v => v.text);
      if (!verses.length) fail(file + " empty chapter " + id + " " + n);
      chapters[n] = verses;
    });
    return { id, chapters };
  });
}

/* Official Declarations: scraped paragraph lists with optional subsection headings */
function odBook(file) {
  const items = JSON.parse(fs.readFileSync(path.join(SRC, file), "utf8"));
  const verses = [], heads = {};
  items.forEach(it => {
    if (it.v != null) verses.push(it.text);
    else if (it.head) heads[verses.length] = it.head; // heading renders before verse `verses.length`
    else fail(file + " unknown item");
  });
  return { verses, heads };
}

/* chunk whole books into files ≤ ~CHUNK_BYTES of serialized JS */
function chunkVolume(vol, books) {
  const chunks = [];
  let cur = [], size = 0;
  const bookSize = b => ("T[" + JSON.stringify(b.id) + "]=").length + JSON.stringify(b.chapters).length + 2;
  books.forEach(b => {
    const s = bookSize(b);
    if (cur.length && size + s > CHUNK_BYTES) { chunks.push(cur); cur = []; size = 0; }
    cur.push(b); size += s;
  });
  if (cur.length) chunks.push(cur);
  return chunks.map((ck, i) => ({ file: "text-" + vol + "-" + (i + 1), books: ck }));
}

/* ---------- build ---------- */
const ot  = volumeBooks("old-testament.json");
const nt  = volumeBooks("new-testament.json");
const bom = volumeBooks("book-of-mormon.json");
const dcSections = loadVol("doctrine-and-covenants.json").sections.map((s, i) => {
  if (s.section !== i + 1) fail("dc section out of order at index " + i);
  return { id: "dc", chapters: { [s.section]: s.verses.map(v => v.text) } };
});
/* D&C is one book — feed as a single "book" so chunking still applies */
const dc = [{ id: "dc", chapters: dcSections.reduce((a, s) => Object.assign(a, s.chapters), {}) }];
const pgp = volumeBooks("pearl-of-great-price.json");
const ods = [
  { id: "od-1", od: odBook("od1.json") },
  { id: "od-2", od: odBook("od2.json") }
];

const manifest = {};
let totalVerses = 0, totalChapters = 0;
function emit(vol, groups) {
  manifest[vol] = [];
  groups.forEach(g => {
    let body = '/* Scripture Launchpad — full text, AUTO-GENERATED by tools/build-text.js — DO NOT EDIT. Text © Intellectual Reserve, Inc. */\n'
      + 'window.SLP_TEXT = window.SLP_TEXT || {};\n(function(){\nvar T = window.SLP_TEXT;\n';
    g.books.forEach(b => {
      body += "T[" + JSON.stringify(b.id) + "]=" + JSON.stringify(b.chapters) + ";\n";
      totalChapters += Object.keys(b.chapters).length;
      totalVerses += Object.keys(b.chapters).reduce((s, n) => s + b.chapters[n].length, 0);
    });
    if (g.od) {
      body += "T[" + JSON.stringify(g.od.id) + "]=" + JSON.stringify({ verses: g.od.verses, heads: g.od.heads }) + ";\n";
      totalChapters += 1; totalVerses += g.od.verses.length;
    }
    body += "})();\n";
    const p = path.join(OUT, g.file + ".js");
    fs.writeFileSync(p, body, "utf8");
    manifest[vol].push(g.file);
    console.log("wrote", g.file + ".js", (fs.statSync(p).size / 1024).toFixed(0) + "KB");
  });
}

emit("ot",  chunkVolume("ot", ot));
emit("nt",  chunkVolume("nt", nt));
emit("bom", chunkVolume("bom", bom));
emit("dc",  chunkVolume("dc", dc));
emit("pgp", chunkVolume("pgp", pgp));

/* ODs ride in their own small file on the dc volume (they are D&C-section-like) */
{
  const files = manifest.dc;
  const name = "text-dc-od";
  let body = '/* Scripture Launchpad — full text, AUTO-GENERATED by tools/build-text.js — DO NOT EDIT. Text © Intellectual Reserve, Inc. */\n'
    + 'window.SLP_TEXT = window.SLP_TEXT || {};\n(function(){\nvar T = window.SLP_TEXT;\n';
  ods.forEach(o => {
    body += "T[" + JSON.stringify(o.id) + "]=" + JSON.stringify({ verses: o.od.verses, heads: o.od.heads }) + ";\n";
    totalChapters += 1; totalVerses += o.od.verses.length;
  });
  body += "})();\n";
  fs.writeFileSync(path.join(OUT, name + ".js"), body, "utf8");
  manifest.dc.push(name);
  console.log("wrote", name + ".js", (fs.statSync(path.join(OUT, name + ".js")).size / 1024).toFixed(0) + "KB");
}

const mf = '/* Scripture Launchpad — text chunk manifest, AUTO-GENERATED by tools/build-text.js — DO NOT EDIT. */\n'
  + 'window.SLP_TEXT_FILES = ' + JSON.stringify(manifest) + ';\n';
fs.writeFileSync(path.join(OUT, "text-manifest.js"), mf, "utf8");
console.log("wrote text-manifest.js");
console.log("---");
console.log("chapters with text:", totalChapters, "| verses:", totalVerses);
