#!/usr/bin/env node
/* Generate sw.js with a precache manifest of every runtime file in this
   folder (index.html, styles.css, app.js, manifest.json, icons/, data/).
   The content hash becomes the cache version, so any content change
   invalidates old caches on the next visit.

   Run:  node tools/build-sw.js      (from the scripture-launchpad folder)
   CI runs this before deploying so the precache list always matches the
   deployed files exactly. Regenerating locally keeps the committed sw.js
   in sync for local testing. */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const FILES = ["index.html", "styles.css", "app.js", "manifest.json"]
  .concat(walk("icons"))
  .concat(walk("data"))
  .filter(f => fs.statSync(path.join(ROOT, f)).isFile());

function walk(dir){
  const base = path.join(ROOT, dir);
  if (!fs.existsSync(base)) return [];
  return fs.readdirSync(base)
    .map(f => dir + "/" + f)
    .filter(f => fs.statSync(path.join(ROOT, f)).isFile());
}

const hash = crypto.createHash("sha256");
FILES.filter(f => f !== "sw.js").sort().forEach(f => {
  hash.update(f); hash.update(fs.readFileSync(path.join(ROOT, f)));
});
const VERSION = "slp-" + hash.digest("hex").slice(0, 12);

const sw = `/* GENERATED by tools/build-sw.js — do not edit by hand.
   Version ${VERSION} */
const VERSION = "${VERSION}";
const ASSETS = ${JSON.stringify(FILES.filter(f => f !== "sw.js"), null, 2).replace(/\n/g, "\n")};
const FONT_HOSTS = ["https://fonts.googleapis.com", "https://fonts.gstatic.com"];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(VERSION).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION && k.startsWith("slp-")).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = FONT_HOSTS.some(h => url.href.startsWith(h));
  if (url.origin !== location.origin && !isFont) return;   /* let everything else hit the network */

  /* navigations: serve the app shell when offline (hash routing = one real page) */
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req).then(res => {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put("index.html", copy));
        return res;
      }).catch(() => caches.match("index.html"))
    );
    return;
  }

  /* everything else: cache-first, fill the cache on the way past */
  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res && (res.ok || res.type === "opaque")) {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
`;

fs.writeFileSync(path.join(ROOT, "sw.js"), sw);
console.log("sw.js written —", VERSION, "·", FILES.length - 1, "precache entries");
