/* GENERATED by tools/build-sw.js — do not edit by hand.
   Version slp-2b0a8c605f99 */
const VERSION = "slp-2b0a8c605f99";
const ASSETS = [
  "index.html",
  "styles.css",
  "app.js",
  "manifest.json",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-192.png",
  "icons/maskable-512.png",
  "data/bom-01-1ne.js",
  "data/bom-02-2ne.js",
  "data/bom-03-jacob-words.js",
  "data/bom-04-mosiah.js",
  "data/bom-05-alma-a.js",
  "data/bom-06-alma-b.js",
  "data/bom-07-helaman.js",
  "data/bom-08-3ne.js",
  "data/bom-09-4ne-mormon-ether.js",
  "data/bom-10-moroni.js",
  "data/canon.js",
  "data/dc-01-foundations.js",
  "data/dc-02-ohio.js",
  "data/dc-03-law-and-spirit.js",
  "data/dc-04-zion.js",
  "data/dc-05-priesthood.js",
  "data/dc-06-persecution.js",
  "data/dc-07-kirtland.js",
  "data/dc-08-liberty.js",
  "data/dc-09-nauvoo.js",
  "data/dc-10-od.js",
  "data/glossary.js",
  "data/nt-01-matt.js",
  "data/nt-02-mark-luke.js",
  "data/nt-03-john.js",
  "data/nt-04-acts.js",
  "data/nt-05-rom-1cor.js",
  "data/nt-06-2cor-col.js",
  "data/nt-07-thes-heb.js",
  "data/nt-08-pet-jude.js",
  "data/nt-09-rev.js",
  "data/ot-01-genesis-a.js",
  "data/ot-02-genesis-b.js",
  "data/ot-03-exodus.js",
  "data/ot-04-leviticus.js",
  "data/ot-05-numbers.js",
  "data/ot-06-deuteronomy.js",
  "data/ot-07-joshua-ruth.js",
  "data/ot-08-judges.js",
  "data/ot-09-1samuel.js",
  "data/ot-10-2samuel.js",
  "data/ot-11-1kings.js",
  "data/ot-12-2kings.js",
  "data/ot-13-1chronicles.js",
  "data/ot-14-2chronicles.js",
  "data/ot-15-ezra-neh-esth.js",
  "data/ot-16-job-a.js",
  "data/ot-17-job-b.js",
  "data/ot-18-psalms-a.js",
  "data/ot-19-psalms-b.js",
  "data/ot-20-psalms-c.js",
  "data/ot-21-psalms-d.js",
  "data/ot-22-proverbs.js",
  "data/ot-23-eccl-song.js",
  "data/ot-24-isaiah-a.js",
  "data/ot-25-isaiah-b.js",
  "data/ot-26-isaiah-c.js",
  "data/ot-27-jeremiah-a.js",
  "data/ot-28-jeremiah-b.js",
  "data/ot-29-lam-ezek-a.js",
  "data/ot-30-ezek-b.js",
  "data/ot-31-ezek-c.js",
  "data/ot-32-dan-hosea.js",
  "data/ot-33-joel-jonah.js",
  "data/ot-34-micah-zeph.js",
  "data/ot-35-hag-mal.js",
  "data/pgp-01-moses.js",
  "data/pgp-02-abraham.js",
  "data/pgp-03-visions.js",
  "data/pgp-04-a-of-f.js",
  "data/text-bom-1.js",
  "data/text-bom-2.js",
  "data/text-bom-3.js",
  "data/text-dc-1.js",
  "data/text-dc-od.js",
  "data/text-manifest.js",
  "data/text-nt-1.js",
  "data/text-nt-2.js",
  "data/text-ot-1.js",
  "data/text-ot-2.js",
  "data/text-ot-3.js",
  "data/text-ot-4.js",
  "data/text-ot-5.js",
  "data/text-pgp-1.js"
];
const FONT_HOSTS = ["https://fonts.googleapis.com", "https://fonts.gstatic.com"];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(VERSION).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION && k.startsWith("slp-")).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = FONT_HOSTS.some(h => url.href.startsWith(h));
  if (url.origin !== location.origin && !isFont) return;   /* let everything else hit the network */

  /* navigations: serve the app shell when offline (hash routing = one real page) */
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req).then(res => {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put("index.html", copy));
        return res;
      }).catch(() => caches.match("index.html"))
    );
    return;
  }

  /* everything else: cache-first, fill the cache on the way past */
  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res && (res.ok || res.type === "opaque")) {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
