/* GENERATED by tools/build-sw.js — do not edit by hand.
   Version slp-ce2ae15c6181 */
const VERSION = "slp-ce2ae15c6181";
const ASSETS = [
  "index.html",
  "styles.css",
  "app.js",
  "manifest.json",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-192.png",
  "icons/maskable-512.png",
  "data/bom-01-1ne.js",
  "data/bom-02-2ne.js",
  "data/bom-03-jacob-words.js",
  "data/bom-04-mosiah.js",
  "data/bom-05-alma-a.js",
  "data/bom-06-alma-b.js",
  "data/bom-07-helaman.js",
  "data/bom-08-3ne.js",
  "data/bom-09-4ne-mormon-ether.js",
  "data/bom-10-moroni.js",
  "data/canon.js",
  "data/glossary.js",
  "data/text-bom-1.js",
  "data/text-bom-2.js",
  "data/text-bom-3.js",
  "data/text-dc-1.js",
  "data/text-dc-od.js",
  "data/text-manifest.js",
  "data/text-nt-1.js",
  "data/text-nt-2.js",
  "data/text-ot-1.js",
  "data/text-ot-2.js",
  "data/text-ot-3.js",
  "data/text-ot-4.js",
  "data/text-ot-5.js",
  "data/text-pgp-1.js"
];
const FONT_HOSTS = ["https://fonts.googleapis.com", "https://fonts.gstatic.com"];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(VERSION).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION && k.startsWith("slp-")).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = FONT_HOSTS.some(h => url.href.startsWith(h));
  if (url.origin !== location.origin && !isFont) return;   /* let everything else hit the network */

  /* navigations: serve the app shell when offline (hash routing = one real page) */
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req).then(res => {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put("index.html", copy));
        return res;
      }).catch(() => caches.match("index.html"))
    );
    return;
  }

  /* everything else: cache-first, fill the cache on the way past */
  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res && (res.ok || res.type === "opaque")) {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
